Feature/implement ssti
pentestThucchienTeam/blog-vul pull request #40
Opened 2021-07-27 05:50 UTC by DoTuan1

2021-07-27 05:55 UTC, S0vvn approved these changes

2021-07-27 14:16 UTC, ThanhTuan1695 requested changes
Bỏ tẤT CẢ CÁC  file backup vào git ignore.

2021-07-27 14:16 UTC, ThanhTuan1695 commented on blogapp/views/register_form.py
> +    username = forms.CharField(label='Username', max_length=None,  widget=forms.TextInput(attrs={'placeholder': 'Username'}))
Chỗ này tại sao ko dùng if else dựa trên setting ssti

2021-07-27 14:16 UTC, ThanhTuan1695 commented on blogapp/views/setting.py
> +		if request.user.username :
tại sao ko lấy user từ session.

2021-07-27 14:16 UTC, ThanhTuan1695 commented on blogapp/views/setting.py
> +			return render(request,self.template_name,{'object_list': self.object_list,'user':ssti})
ủa sao render mỗi cái user ko à.

2021-07-27 14:16 UTC, ThanhTuan1695 commented on blogapp/views/setting.py
> +				from core.lib import jwt_vul
tại sao lại đổi khúc này khúc này có ảnh hưởng gì ko?

2021-07-27 14:16 UTC, ThanhTuan1695 commented on blogapp/views/setting.py
> +				from core.lib import jwt_vul
tất cả các import có thẻ cho lên đầu không?

2021-07-27 14:20 UTC, DoTuan1 commented on blogapp/views/register_form.py
> +    username = forms.CharField(label='Username', max_length=None,  widget=forms.TextInput(attrs={'placeholder': 'Username'}))
chỗ này em sửa để tăng cho cái user dài ra thì để em làm if else.

2021-07-27 14:23 UTC, ThanhTuan1695 commented on blogapp/views/register_form.py
> +    username = forms.CharField(label='Username', max_length=None,  widget=forms.TextInput(attrs={'placeholder': 'Username'}))
trường hợp prevent thì sao?

2021-07-28 09:53 UTC, DoTuan1 commented on blogapp/views/register_form.py
> +    username = forms.CharField(label='Username', max_length=None,  widget=forms.TextInput(attrs={'placeholder': 'Username'}))
nếu mà prevent thì mình có thể chỉnh để nó hạn chế kí tự lại để hạn chế những payload nhiều kí tự

2021-07-28 09:54 UTC, DoTuan1 commented on blogapp/views/setting.py
> +				from core.lib import jwt_vul
em cho hết lên đầu r a.

2021-07-28 12:49 UTC, ThanhTuan1695 approved these changes

2021-07-28 12:53 UTC, ThanhTuan1695 reviewed
xóa hết file .bak đi nào

2021-07-28 13:12 UTC, Tu4n4nh approved these changes

2021-07-28 13:13 UTC, merged