feature/doi_url_image
pentestThucchienTeam/blog-vul pull request #52
Opened 2021-09-01 11:41 UTC by Tu4n4nh

2021-09-02 09:36 UTC, DoTuan1 reviewed
Em thấy khá là oke rồi nhưng mình nên thêm 1 thẻ "<a>" chỗ ảnh để nhấn vào ảnh là ra luôn ảnh to bên ngoài.

2021-09-02 11:06 UTC, 0n3dream approved these changes

2021-09-02 13:37 UTC, ThanhTuan1695 requested changes

2021-09-02 13:37 UTC, ThanhTuan1695 commented on blogapp/views/profile.py
> +        print(imageName)
xóa?

2021-09-02 13:40 UTC, ThanhTuan1695 requested changes

2021-09-02 13:40 UTC, ThanhTuan1695 commented on blogapp/views/uploads.py
> +class uploadView(View):
upload avatar chứ sao là view??

2021-09-02 13:46 UTC, Tu4n4nh commented on blogapp/views/uploads.py
> +class uploadView(View):
Ý là nó là cái view của upload á anh :)) giống mấy cái khác cũng v í

2021-09-04 15:14 UTC, ThanhTuan1695 approved these changes

2021-09-04 15:17 UTC, merged