Create_model
pentestThucchienTeam/blog-vul pull request #6
Opened 2021-05-21 05:22 UTC by DoTuan1

Mọi  người verify lại cho em vơi ạ

2021-05-21 05:31 UTC, Wolfasterest approved these changes

2021-05-23 09:00 UTC, ThanhTuan1695 reviewed
sửa lại các cmt

2021-05-23 09:10 UTC, ThanhTuan1695 reviewed
fix các cmt đi.

2021-05-23 09:10 UTC, ThanhTuan1695 commented on blogapp/migrations/0002_profile.py
> +
Chưa thấy khóa ngoại ở đây. Làm sao để e biết profile thuộc user nào

2021-05-23 09:10 UTC, ThanhTuan1695 commented on blogapp/migrations/0003_comment.py
> +                ('username', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cmt_user', to='blogapp.user')),
không thấy khóa ngoại ở đây. làm sao đẻ e biết học cmt trên abif viết nào. và không biết là ai cmt. 
giả sử user đã có trên hệ thống thì làm sao mà xác đi định

2021-05-23 09:16 UTC, DoTuan1 commented on blogapp/migrations/0003_comment.py
> +                ('username', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cmt_user', to='blogapp.user')),
tại đàu em dùng foreign nhưng nó gợi ý dùng onetofeil ấy anh

2021-05-23 09:17 UTC, ThanhTuan1695 commented on blogapp/migrations/0003_comment.py
> +                ('username', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cmt_user', to='blogapp.user')),
nên dùng user_id 
chứ ko nên dùng username

2021-05-24 09:42 UTC, ThanhTuan1695 requested changes

2021-05-24 09:42 UTC, ThanhTuan1695 commented on blogapp/migrations/0001_initial.py
> +        migrations.CreateModel(
tách ra rồi thì nên xóa mấy cái này đi.

2021-05-24 11:11 UTC, Wolfasterest approved these changes

2021-05-26 10:17 UTC, Tu4n4nh reviewed
- [x] ![image](https://user-images.githubusercontent.com/22276823/119643588-6e564f80-be0b-11eb-81f6-d27cc561e6e8.png)

Post đang bị `Catalogies:` đang bị đánh dấu là không được trùng

2021-05-26 11:10 UTC, DoTuan1 commented
> * [ ]  ![image](https://user-images.githubusercontent.com/22276823/119643588-6e564f80-be0b-11eb-81f6-d27cc561e6e8.png)
> 
> Post đang bị `Catalogies:` đang bị đánh dấu là không được trùng

Done
![Screenshot 2021-05-26 175245](https://user-images.githubusercontent.com/63194321/119650129-a8484580-be4d-11eb-8b25-ed3358e196aa.png)
![Screenshot 2021-05-26 175306](https://user-images.githubusercontent.com/63194321/119650140-aa120900-be4d-11eb-9283-c1b21352b035.png)

2021-05-27 14:57 UTC, Tu4n4nh reviewed
Fĩx conflict, đã check chạy okie

2021-05-27 15:21 UTC, Tu4n4nh approved these changes

2021-05-27 15:25 UTC, ThanhTuan1695 approved these changes

2021-05-27 15:25 UTC, merged